In [33]:
# %pip install requests
# %pip install bs4
# %pip install pandas
# %pip install lxml

In [49]:
import requests # Fazer uma solicitação HTTP
from bs4 import BeautifulSoup # Para a manipulação de HTML
import pandas as pd # Criação de dataframes
import lxml
from io import StringIO
import re

In [121]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO
from IPython.display import display

def extrair_varias_tabelas(url):
    # Fazendo a requisição HTTP para obter o conteúdo da página
    response = requests.get(url)

    # Verificando se a requisição foi bem-sucedida
    if response.status_code == 200:
        # Parseando o conteúdo da página com BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # Encontrando a div com id 'parent-fieldname-text'
        div_content = soup.find('div', id='parent-fieldname-text')
        
        if div_content:
            # Extraindo todas as tags <strong> e as tabelas dentro da div
            strong_tags = div_content.find_all('strong')
            tables = div_content.find_all('table')
            
            # Criando um dicionário para armazenar DataFrames
            dataframes = {}
            
            # Iterando sobre as tabelas encontradas e transformando em DataFrames
            for idx, (strong, table) in enumerate(zip(strong_tags, tables)):
                table_html = str(table)
                df = pd.read_html(StringIO(table_html))[0]  # Transformando a tabela HTML em DataFrame
                
                # Criando um nome para o DataFrame
                name = f"DataFrame_{idx+1}"
                # Armazenando o DataFrame no dicionário
                dataframes[name] = df
                
                # Exibindo o conteúdo da tag <strong>
                print(f"\nConteúdo da tag <strong> {idx+1}:")
                print(strong.get_text(strip=True))
                
                # Exibindo o DataFrame
                print(f"\nDisplaying {name}:")
                display(df)
                
            return dataframes
        else:
            print("Div com o id 'parent-fieldname-text' não encontrada.")
            return {}
    else:
        print(f"Erro ao acessar a página: Status code {response.status_code}")
        return {}

# URL do exemplo
url_valores = "https://www.gov.br/antt/pt-br/assuntos/rodovias/concessionarias/lista-de-concessoes/contratos-encerrados/crt/tarifas-de-pedagio"

# Extraindo e exibindo os DataFrames
dataframes = extrair_varias_tabelas(url_valores)

Conteúdo da tag <strong> 1:
Tabela 1: Tarifas na Praça Principal (PN-1) Imbariê

Displaying DataFrame_1:

,0,1,2,3,4,5
0,NaN,Tipo de Veiculo,Número de Eixos,Rodagem,Multiplicador da Tarifa,Valores praticados (R$)
1,1.0,"Automóvel, caminhonete e furgão",2,Simples,1,1880
2,2.0,"Caminhão leve, ônibus, caminhão-trator e furgão",2,Dupla,2,3760
3,3.0,Automóvel e caminhonete com semi-reboque,3,Simples,15,2820
4,4.0,"Caminhão, caminhão-trator, caminhão-trator com...",3,Dupla,3,5640
5,5.0,Automóvel e caminhonete com reboque,4,Simples,2,3760
6,6.0,Caminhão com reboque e caminhão-trator com sem...,4,Dupla,4,7520
7,7.0,Caminhão com reboque e caminhão-trator com sem...,5,Dupla,5,9400
8,8.0,Caminhão com reboque e caminhão-trator com sem...,6,Dupla,6,11280
9,9.0,"Motocicletas, motonetas e bicicletas motorizadas",2,Simples,05,940

Conteúdo da tag <strong> 2:
Tabela 2: Tarifas nas Praças Auxiliares (PA-1 e PA-2) Trevo Sta. Guilhermina e Trevo Sto. Aleixo

Displaying DataFrame_2:

,0,1,2,3,4,5
0,NaN,Tipo de Veiculo,Número de Eixos,Rodagem,Multiplicador da Tarifa,Valores praticados (R$)
1,1.0,"Automóvel, caminhonete e furgão",2,Simples,1,1310
2,2.0,"Caminhão leve, ônibus, caminhão-trator e furgão",2,Dupla,2,2620
3,3.0,Automóvel e caminhonete com semi-reboque,3,Simples,15,1965
4,4.0,"Caminhão, caminhão-trator, caminhão-trator com...",3,Dupla,3,3930
5,5.0,Automóvel e caminhonete com reboque,4,Simples,2,2620
6,6.0,Caminhão com reboque e caminhão-trator com sem...,4,Dupla,4,5240
7,7.0,Caminhão com reboque e caminhão-trator com sem...,5,Dupla,5,6550
8,8.0,Caminhão com reboque e caminhão-trator com sem...,6,Dupla,6,7860
9,9.0,"Motocicletas, motonetas e bicicletas motorizadas",2,Simples,05,655

In [104]:
# url_valores = "https://www.gov.br/antt/pt-br/assuntos/rodovias/concessionarias/lista-de-concessoes/contratos-encerrados/crt/tarifas-de-pedagio"

# tabela_autopista = extrair_varias_tabelas(url_valores)
# ############################################################################################################################################

# display(tabela_autopista)

<strong> (1): Tabela 1: Tarifas na Praça Principal (PN-1) Imbariê
Tabela após <strong> (1):
<table>
<tbody>
<tr>
<td>
<p><span> </span></p>
</td>
<td>
<p><span>Tipo de Veiculo</span></p>
</td>
<td>
<p><span>Número de Eixos</span></p>
</td>
<td>
<p><span>Rodagem</span></p>
</td>
<td>
<p><span>Multiplicador da Tarifa</span></p>
</td>
<td>
<p><span>Valores praticados (R$)</span></p>
</td>
</tr>
<tr>
<td>
<p>1</p>
</td>
<td>
<p>Automóvel, caminhonete e furgão</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p>Simples</p>
</td>
<td>
<p>1</p>
</td>
<td>
<p>18,80</p>
</td>
</tr>
<tr>
<td>
<p>2</p>
</td>
<td>
<p>Caminhão leve, ônibus, caminhão-trator e furgão</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p>37,60</p>
</td>
</tr>
<tr>
<td>
<p>3</p>
</td>
<td>
<p>Automóvel e caminhonete com semi-reboque</p>
</td>
<td>
<p>3</p>
</td>
<td>
<p>Simples</p>
</td>
<td>
<p>1,5</p>
</td>
<td>
<p>28,20</p>
</td>
</tr>
<tr>
<td>
<p>4</p>
</td>
<td>
<p>Caminhão, caminhão-trator, caminhão-trator com semi-reboque e ônibus</p>
</td>
<td>
<p>3</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>3</p>
</td>
<td>
<p> 56,40</p>
</td>
</tr>
<tr>
<td>
<p>5</p>
</td>
<td>
<p>Automóvel e caminhonete com reboque</p>
</td>
<td>
<p>4</p>
</td>
<td>
<p>Simples</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p>37,60</p>
</td>
</tr>
<tr>
<td>
<p>6</p>
</td>
<td>
<p>Caminhão com reboque e caminhão-trator com semi-reboque</p>
</td>
<td>
<p>4</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>4</p>
</td>
<td>
<p>75,20</p>
</td>
</tr>
<tr>
<td>
<p>7</p>
</td>
<td>
<p>Caminhão com reboque e caminhão-trator com semi-reboque</p>
</td>
<td>
<p>5</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>5</p>
</td>
<td>
<p>94,00</p>
</td>
</tr>
<tr>
<td>
<p>8</p>
</td>
<td>
<p>Caminhão com reboque e caminhão-trator com semi-reboque</p>
</td>
<td>
<p>6</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>6</p>
</td>
<td>
<p>112,80</p>
</td>
</tr>
<tr>
<td>
<p>9</p>
</td>
<td>
<p>Motocicletas, motonetas e bicicletas motorizadas</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p>Simples</p>
</td>
<td>
<p>0,5</p>
</td>
<td>
<p>9,40</p>
</td>
</tr>
</tbody>
</table>

<strong> (2): Tabela 2: Tarifas nas Praças Auxiliares (PA-1 e PA-2) Trevo Sta. Guilhermina e Trevo Sto. Aleixo
Tabela após <strong> (2):
<table>
<tbody>
<tr>
<td>
<p><span> </span></p>
</td>
<td>
<p><span>Tipo de Veiculo</span></p>
</td>
<td>
<p><span>Número de Eixos</span></p>
</td>
<td>
<p><span>Rodagem</span></p>
</td>
<td>
<p><span>Multiplicador da Tarifa</span></p>
</td>
<td>
<p><span>Valores praticados (R$)</span></p>
</td>
</tr>
<tr>
<td>
<p>1</p>
</td>
<td>
<p>Automóvel, caminhonete e furgão</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p>Simples</p>
</td>
<td>
<p>1</p>
</td>
<td>
<p>13,10</p>
</td>
</tr>
<tr>
<td>
<p>2</p>
</td>
<td>
<p>Caminhão leve, ônibus, caminhão-trator e furgão</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p> 26,20</p>
</td>
</tr>
<tr>
<td>
<p>3</p>
</td>
<td>
<p>Automóvel e caminhonete com semi-reboque</p>
</td>
<td>
<p>3</p>
</td>
<td>
<p>Simples</p>
</td>
<td>
<p>1,5</p>
</td>
<td>
<p>19,65</p>
</td>
</tr>
<tr>
<td>
<p>4</p>
</td>
<td>
<p>Caminhão, caminhão-trator, caminhão-trator com semi-reboque e ônibus</p>
</td>
<td>
<p>3</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>3</p>
</td>
<td>
<p> 39,30</p>
</td>
</tr>
<tr>
<td>
<p>5</p>
</td>
<td>
<p>Automóvel e caminhonete com reboque</p>
</td>
<td>
<p>4</p>
</td>
<td>
<p>Simples</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p>26,20</p>
</td>
</tr>
<tr>
<td>
<p>6</p>
</td>
<td>
<p>Caminhão com reboque e caminhão-trator com semi-reboque</p>
</td>
<td>
<p>4</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>4</p>
</td>
<td>
<p>52,40</p>
</td>
</tr>
<tr>
<td>
<p>7</p>
</td>
<td>
<p>Caminhão com reboque e caminhão-trator com semi-reboque</p>
</td>
<td>
<p>5</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>5</p>
</td>
<td>
<p>65,50</p>
</td>
</tr>
<tr>
<td>
<p>8</p>
</td>
<td>
<p>Caminhão com reboque e caminhão-trator com semi-reboque</p>
</td>
<td>
<p>6</p>
</td>
<td>
<p>Dupla</p>
</td>
<td>
<p>6</p>
</td>
<td>
<p>78,60</p>
</td>
</tr>
<tr>
<td>
<p>9</p>
</td>
<td>
<p>Motocicletas, motonetas e bicicletas motorizadas</p>
</td>
<td>
<p>2</p>
</td>
<td>
<p>Simples</p>
</td>
<td>
<p>0,5</p>
</td>
<td>
<p>6,55</p>
</td>
</tr>
</tbody>
</table>

None